cd ~/
git init
git remote add origin https://github.com/sevaivanov/archlinux-setup.git
git fetch
git checkout -t origin/master
git submodule init
git submodule update

# Unit files
systemctl --user daemon-reload

# Login script
/bin/bash ~/.xprofile
